Repository netlify/gh-release-fetch, pull requests merged in 2021-06, with the labels that each got.

#21 chore: add fossa license scanning
  .github/workflows/fossa.yml
Labels: type: bot

#26 chore: add pr labeler
  .github/workflows/labeler.yml
Labels: type: chore

#25 chore: add renovate config
  renovate.json5
Labels: type: chore

#24 chore: add eslint-config-node
  .editorconfig
  .eslintrc.js
  .gitattributes
  .github/workflows/main.yml
  .github/workflows/release-please.yml
  .gitignore
  .prettierrc.json
  commitlint.config.js
  package-lock.json
  package.json
  src/index.spec.ts
  src/index.ts
  tsconfig.json
  tslint.json
Labels: status: blocked, type: chore
